"""
Pull Request Template Generation

Generates comprehensive PR descriptions for automated fixes.
"""

from typing import Any, Dict
from datetime import datetime


class PRTemplateGenerator:
    """Generates PR descriptions and titles."""

    @staticmethod
    def generate_pr_title(finding: Any) -> str:
        """
        Generate PR title.

        Args:
            finding: SonarQubeFinding object

        Returns:
            PR title string
        """
        severity_emoji = {
            "CRITICAL": "🔴",
            "HIGH": "🟠",
            "MEDIUM": "🟡",
            "LOW": "🟢"
        }

        emoji = severity_emoji.get(finding.severity, "🔧")
        return f"{emoji} Fix {finding.severity}: {finding.rule_name}"

    @staticmethod
    def generate_pr_body(
        finding: Any,
        fix_result: Any,
        risk_assessment: Any
    ) -> str:
        """
        Generate comprehensive PR description.

        Args:
            finding: SonarQubeFinding object
            fix_result: FixResult object
            risk_assessment: RiskAssessment object

        Returns:
            Markdown-formatted PR description
        """

        # Format test suggestions
        test_section = ""
        if fix_result.test_suggestions:
            test_items = "\n".join([f"- {test}" for test in fix_result.test_suggestions])
            test_section = f"""
### 🧪 Testing Recommendations

{test_items}
"""

        # Format validation checks
        validation_checks = ""
        if fix_result.validation.checks_passed:
            passed = "\n".join([f"- ✅ {check}" for check in fix_result.validation.checks_passed])
            validation_checks = f"\n**Validation Checks Passed:**\n{passed}\n"

        if fix_result.validation.warnings:
            warnings = "\n".join([f"- ⚠️ {warning}" for warning in fix_result.validation.warnings])
            validation_checks += f"\n**Warnings:**\n{warnings}\n"

        body = f"""## 🔍 SonarQube Finding Resolution

### Issue Details
- **Finding ID**: `{finding.key}`
- **Severity**: **{finding.severity}**
- **Rule**: `{finding.rule_key}` - {finding.rule_name}
- **File**: `{finding.file_path}:{finding.line}`
- **Priority**: **{risk_assessment.priority}** (Risk Score: {risk_assessment.risk_score:.1f}/10)

### 🎯 Root Cause
{finding.message}

**Business Context:** {risk_assessment.business_context}

### ✅ Fix Applied

{fix_result.explanation}

**Code Changes:**
```diff
{fix_result.diff}
```
{test_section}
### 📊 Impact Assessment

**Risk Reduction:** {finding.severity} → RESOLVED

**Risk Breakdown:**
- Exploitability: {risk_assessment.exploitability}/10
- Business Impact: {risk_assessment.impact}/10
- Exposure: {risk_assessment.exposure}/10

**Justification:** {risk_assessment.justification}

**Breaking Changes:** None (maintains backward compatibility)

### ✨ Validation
{validation_checks}

### 🤖 Agent Metadata
- **Confidence**: {fix_result.confidence:.0%}
- **Model**: deepseek-coder-v2:33b
- **Recommended SLA**: {risk_assessment.recommended_sla}
- **Generated**: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}

---

**Review Checklist:**
- [ ] Fix resolves the SonarQube finding
- [ ] No new issues introduced
- [ ] Tests cover edge cases (if applicable)
- [ ] Code follows project conventions

---
*This PR was automatically generated by [SonarQube Analysis Agent](https://github.com/yourorg/sonarqube-agent) v1.0*
"""

        return body

    @staticmethod
    def get_pr_labels(finding: Any, risk_assessment: Any) -> list:
        """
        Generate appropriate labels for the PR.

        Args:
            finding: SonarQubeFinding object
            risk_assessment: RiskAssessment object

        Returns:
            List of label names
        """
        labels = [
            "sonarqube",
            "automated-fix",
            f"severity-{finding.severity.lower()}",
            f"priority-{risk_assessment.priority.lower()}"
        ]

        # Add type-specific labels
        rule_key = finding.rule_key.lower()

        if "security" in rule_key or "vulnerability" in finding.rule_name.lower():
            labels.append("security")

        if "sql" in rule_key or "injection" in finding.rule_name.lower():
            labels.append("security-vulnerability")

        if "null" in rule_key or "npe" in rule_key:
            labels.append("bug-fix")

        return labels
